services:
  alooha_proxy:
    build:
      context: .
    container_name: alooha_proxy
    volumes:
      - '.:/app'
    ports:
      - "8198:8000"
      - "11001:11001"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    working_dir: /app

