services:
  alooha_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alooha_proxy
    env_file:
      - .env
    volumes:
      - './app:/home/alooha/app'
    ports:
      - "8198:8000"
      - "11001:11001"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    working_dir: /app
  alooha_proxy_db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Psql.Dockerfile
    container_name: alooha_proxy_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - './alooha_proxy_db_data:/var/lib/postgresql/data'    
